# Generated by Django 5.2.4 on 2025-08-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=255, unique=True)),
                ('submittedBy', models.CharField(max_length=255)),
                ('submittedDate', models.DateField()),
                ('fields', models.JSONField()),
                ('status', models.CharField(default='Saved', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
