# Generated by Django 5.2.4 on 2025-08-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0002_wheelspecification_delete_formdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wheelspecification',
            name='fields',
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='condemningDia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='lastShopIssueSize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wheelspecification',
            name='treadDiameterNew',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
